[tool.poetry]
name = "subb"
version = "0.1.0"
description = ""
authors = ["Kenta Fukuhara <105337464+KAkikakuFukuhara@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
subc = {path = "pkgs/subc", optional = true, develop = true}

[tool.poetry.extras]
exe = ["subc"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
